NAME = libft.a

OBJ = $(SRC:%.c=%.o)

SRC = ft_putchar.c ft_putstr.c ft_tolower.c ft_toupper.c ft_strlen.c \
	  ft_memset.c ft_strcpy.c ft_isascii.c ft_isalpha.c ft_isdigit.c \
	  ft_isalnum.c ft_isprint.c ft_putchar_fd.c ft_putstr_fd.c \
	  ft_putendl.c ft_putendl_fd.c ft_strdup.c ft_bzero.c ft_putnbr.c \
	  ft_strchr.c ft_strrchr.c ft_atoi.c ft_strdel.c ft_memcpy.c \
	  ft_memalloc.c ft_strclr.c ft_strncpy.c ft_memccpy.c ft_memmove.c \
	  ft_memchr.c ft_memcmp.c ft_strcat.c ft_strncat.c \
	  ft_strstr.c ft_strnstr.c ft_strcmp.c ft_strncmp.c ft_memdel.c \
	  ft_strnew.c \
	  ft_strequ.c ft_strnequ.c ft_strsub.c ft_strjoin.c ft_strtrim.c \
	  ft_strsplit.c ft_itoa.c ft_putnbr_fd.c \
	  ft_putnbr_endl.c ft_strdupchr.c ft_strlenchr.c ft_strndup.c \
	  ft_itoa_base.c ft_printbase_up.c ft_printbase_down.c

CPP = gcc

FLAGS = -Werror -Wextra -Wall

all: $(NAME)

$(NAME): $(OBJ)
	ar rc $(NAME) $(OBJ)

$(OBJ): $(SRC)
	$(CPP) $(FLAGS) -c $(SRC) -I includes

clean:
	/bin/rm -rf $(OBJ)

fclean: clean
	/bin/rm -rf $(NAME)

re: clean fclean all
